## Configuration File for Visualizing the Predictions of the Climatological Ensemble and a Selected RFC Model ##

# Set the path and file names of the ground truth
PATH_ground_truth :  './Data_in_csv_Format/'
ifile_ground_truth_cold_waves : 'eobsv23e_tg_3E_20E_45N_60N_1950_2020_binary_cold_waves_lead_time_14d.csv'

# Set the path and file names of the climatological ensemble and its cold wave days predictions
PATH_climatological_ensemble : './Climatological_Ensemble/'
ifile_climatological_ensemble_cold_waves : 'daily_climatological_ensemble_cold_waves_Cold_Wave_2000_2020.csv'

# Set the path and file names of the RFC model's predictions 
PATH_predictions_rfc : './Predictions_Statistics_as_Predictors/'
ifile_predictions_rfc : 'RFC_predictions_cold_wave_days_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_lead_14d_validation_2000_2020.csv'

# Set the path to the desired output folders
PATH_plots : './Plotting_Visualization_Prediction_Ensembles/'

# Set the quantiles used for variability estimation and plotting
upper_quantile: 0.95
lower_quantile: 0.05

# Set the lead time 
lead_time : 14

# Set additional information which cannot be inferred from the data directly (keep it short but still informative)
rfc_model_name : 'RFC_stat_all'
binary_ground_truth : 'cold_wave_days'

# Set the details to the desired winters
start_year_of_first_winter : 2000
start_year_of_last_winter : 2019

start_month_winter : 11
start_day_winter: 1

end_month_winter: 4
end_day_winter: 30
