## Configuration File for Comparing the CRPS values for the climatological ensemble and the QRF models ## 

# Set the path and file names of the ground truth
PATH_ground_truth : './Data_in_csv_Format/'
ifile_ground_truth : 'eobsv23e_tg_3E_20E_45N_60N_1950_2020_only_Nov_Apr_lead_time_14d.csv'

# Set the path and file names of the CRPS values of the climatological_ensemble 
PATH_climatological_ensemble_crps : './Skill_Assessment_with_CRPS/'
ifile_climatological_ensemble_crps : 'Climatological_timeseries_CRPS_av_tg_3E_20E_45N_60N_input_av_tg_3E_20E_45N_60N_2000_2020.csv'

# Set the path and file names of the CRPS values of the predictions
PATHs_prediction_crps : ['./Skill_Assessment_with_CRPS/Data_CRPS_All_Grid_Points_of_Field_as_Predictors/','./Skill_Assessment_with_CRPS/Data_CRPS_All_Grid_Points_of_Field_as_Predictors/', './Skill_Assessment_with_CRPS/Data_CRPS_Statistics_as_Predictors/','./Skill_Assessment_with_CRPS/Data_CRPS_Statistics_as_Predictors/', './Skill_Assessment_with_CRPS/Data_CRPS_PCA_as_Predictors/', './Skill_Assessment_with_CRPS/Data_CRPS_PCA_as_Predictors/']

ifiles_prediction_crps : ['QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_field_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_lead_14d_2000_2020.csv','QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_field_u10_z100_z250_60W_60E_20N_80N_lead_14d_2000_2020.csv','QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_lead_14d_2000_2020.csv','QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_statistics_u10_z100_z250_60W_60E_20N_80N_lead_14d_2000_2020.csv', 'QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_pca_n10_u10_z100_z250_z500_z850_t850_H850_u300_msl_60W_60E_20N_80N_lead_14d_2000_2020.csv',  'QRF_CRPS_av_tg_3E_20E_45N_60N_input_month_pca_n10_u10_z100_z250_60W_60E_20N_80N_lead_14d_2000_2020.csv']

# Set the path to the desired output folder
PATH_plots : './Plotting_Difference_CRPS_CRPSS/'

# Set the lead time
lead_time : 14

# Set the index (position in the list of input files above) for the representative models for plotting
index_representative_qrf_model : 2

# Set additional information which cannot be inferred from the data directly (keep it short but still informative)
qrf_model_names : 'QRF_all_grid_points_pca_stat_all_sel'
representative_qrf_model : 'QRF_stat_all_14d_lead'
continuous_ground_truth : 'av_tg'
unit_continuous_ground_truth : 'K'

# Set additional details to be shown on the plots
input_data_label_climatological_ensemble : 'Climatological Ensemble' # if it's really long, put | in the string to create a linebreak in it, e.g. 'Climatological | Ensemble'
input_data_labels_prediction_crps:  ['QRF_all', 'QRF_sel' , 'QRF_stat_all', 'QRF_stat_sel', 'QRF_pca_all', 'QRF_pca_sel']

# Set the details to the desired winters
start_year_of_first_winter : 2000
start_year_of_last_winter : 2019

start_month_winter : 11
start_day_winter: 1

end_month_winter: 4
end_day_winter: 30
